#' Simplify IMGT FASTA Headers
#'
#' Overwrites IMGT FASTA headers with the V, D, or J gene name.
#'
#' IMGT FASTA headers contain many useful fields that tell you at a glance
#'   information about whether a gene is functional, a pseudogene, or an ORF.
#'   There is also information about the positions where genes start and end
#'   within a given sequence, as well as a verbose name for each sequence. At
#'   times it is better to work with FASTA headers with simple names, for
#'   example, when using them programmatically. This function simplifies IMGT
#'   reference sequence FASTA headers to a V, D, or J gene name only.
#'
#' @param .file A character string. File path to a FASTA formatted sequence file
#'   containing IMGT reference sequences. Alternatively a character vector R
#'   object generated by first reading in the FASTA with `readLines()`.
#' @examples
#' \dontrun{fasta <- data(vgenes)
#'   new_fasta <- fix_imgt_fasta_headers(fasta)
#'   writeLines(new_fastq)}
#'
#' @author Christopher Parks (caparks2@gmail.com)
#' @export
fix_imgt_fasta_headers <- function(.file) {

  if (is.character(.file)) {
    data <- readLines(.file, warn = FALSE)
  } else {
    data <- .file
  }

  find_text <- paste0(
    "(?<=>IMGT[[:digit:]]*\\|)",
    "[[:alpha:]]{4}[[:digit:]]{1,2}\\*[[:digit:]]{1,2}",
    "|[[:alpha:]]{4}[[:digit:]]{1,2}-[[:digit:]]{1,2}\\*[[:digit:]]{1,2}",
    "(?=\\|[[:alpha:]].*\\|)"
  )

  data[grepl(">", data)] <- paste0(
    ">", regmatches(data, regexpr(find_text, data, perl = TRUE))
  )
  return(data)
}
