#' @param .x A character vector. File path or URL to a FASTA formatted
#'   sequence file containing IMGT reference sequences. Alternatively, a
#'   character vector generated by first manually reading in the FASTA file
#'   with `readLines()`.
#'
#' @examples
#' # Fetch from IMGT and simplify headers
#' \dontrun{
#' vgenes <- readLines(
#'   paste0(
#'     "https://www.imgt.org/download/V-QUEST/IMGT_V-QUEST",
#'     "_reference_directory/Homo_sapiens/TR/TRBV.fasta"
#'   )
#' )
#' }
