#' Simplify IMGT FASTA Headers
#'
#' Overwrites IMGT FASTA headers with the V, D, or J gene name.
#'
#' IMGT FASTA headers contain many useful fields that tell you at a glance
#'   information about whether a gene is functional, a pseudogene, or an ORF.
#'   There is also information about the positions where genes start and end
#'   within a given sequence, as well as a verbose name for each sequence. At
#'   times it is helpful to work with FASTA headers with simple names, for
#'   example, when using them programmatically. This function simplifies IMGT
#'   reference sequence FASTA headers to a V, D, or J gene name only.
#'
#' @param .x A character vector of FASTA formatted IMGT reference sequences,
#'   first generated by manually reading in the FASTA file
#'   with `readLines()` or with `get_imgt_ref_seqs()`
#' @param .include_species Logical. Indicates whether to include the species
#'   name in the simplified header output.
#'
#' @returns A character vector of FASTA formatted IMGT reference seqeuences of
#'  same length as `.x` with headers reduced to gene names (with optional
#'  species).
#'
#' @examples
#' # Verbose headers
#' head(vgenes)
#'
#' # Simplified headers
#' imgt_simple_headers(head(vgenes))
#'
#' # Simplified headers with species name
#' imgt_simple_headers(head(vgenes), .include_species = TRUE)
#'
#' @author Christopher Parks
#'
#' @family IMGT
#' @references
#' https://www.imgt.org/IMGTindex/Fasta.php
#'
#' @export
imgt_simple_headers <- function(.x, .include_species = FALSE) {

  if (!(any(grepl("^>", .x)) && any(grepl("\\|", .x)))) {
    rlang::abort(
      paste(
        ".x must be a character vector of FASTA formatted IMGT",
        "reference sequences."
      )
    )
  }

  .fasta <- .x
  .header_lines <- grep(">", .fasta)
  .fields <- strsplit(.fasta[.header_lines], "\\|")

  if (!.include_species) {
    .gene_names <- sapply(.fields, function(.fields) .fields[2])
  } else {
    .gene_names <- paste(
      sapply(.fields, function(.fields) .fields[3]),
      sapply(.fields, function(.fields) .fields[2])
    )
  }

  .fasta[.header_lines] <- .gene_names
  return(.fasta)
}
